[app] Do not print messages on startup and do not reference System.Management.Automation.
Since latest commit, vvvvc throws "[ERR] Compile: Unhandled exception. VL.Lang.Platforms.Roslyn.EmitException: error CS1705: Assembly 'Velopack' with identity 'Velopack, Version=0.0.0.0, Culture=neutral, PublicKeyToken=5a523ff9c49fd93d' uses 'NuGet.Versioning, Version=6.14.0.116, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'NuGet.Versioning' with identity 'NuGet.Versioning, Version=6.12.1.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35'"